config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/signup',  to: 'users#new'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>

   

<div class="container">
  <h3>Resources List</h3>    
  <p>Please checkout the following resources.</p>
  <dl>
    <dt>Contacts</dt>
    <dd>- <a href="mailto:rogerne@btinternet.com">rogerne@btinternet.com</a></dd>
    <dd>- @ruuseukdee</dd>    
    <dt>Repositories</dt>
    <dd>- <a href="https://bitbucket.org/dashboard/overview">Bitbucket</a></dd>
    <dd>- <a href="https://github.com/rogerne">Github</a></dd>
  </dl>     
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
	<h1>Welcome to the Base App</h1>

	<h3>
    This is the home page for you Basic Rails application. The base application contains the following features.<br>
  </h3>
   <ul class="list-group list-group-flush">
	  <li class="list-group-item">Bootstrap styling</li>
	  <li class="list-group-item">User sign in</li>
	  <li class="list-group-item">An authentication model</li>
	  <li class="list-group-item">Account activation by email</li>
	  <li class="list-group-item">A guest user feature</li>
	</ul>

	<br>
	<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
	<br>
	<%= link_to "Guest Login", users_path, method: :post, class: "btn btn-lg btn-primary" %>

</div>