config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/signup',  to: 'users#new'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
end

app/views/layouts/_debug.html.erb
<div class="container">
	<%= debug(params) if Rails.env.development? %>
</div>

app/views/layouts/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-bottom ">
	<div class="white-text">
    A Template Ruby on Rails appliction by <a href="mailto:rogerne@btinternet.com">Neil Rogers</a>.
  </div>
	<ul class="navbar-nav ml-auto">
    <li class="nav-item active">
      <%= link_to "About", about_path, :class => "nav-link" %>
    </li>
    <li class="nav-item active">
      <%= link_to "Help", help_path, :class => "nav-link" %>
    </li>
  </ul>
</nav>

app/views/layouts/_navigation_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-between">
  <%= link_to "Base App", root_path, :class => "navbar-brand" %>
    <ul class="navbar-nav ml-auto">
    <li class="nav-item active">
      <%= link_to "Home", root_path, :class => "nav-link" %>
    </li>
  </ul>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav-bar-collapse" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <% if logged_in? %>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <%= link_to "Users", users_path, :class => "nav-link" %>
      </li>
    </ul>
    <div class="dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        
        <%= current_user.user_name %>
      </a>

      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

        <li><%= link_to "Profile", current_user, class: 'dropdown-item' %></li>
        <li><%= link_to "Settings", edit_user_path(current_user), class: 'dropdown-item' %></li>
        <div class="dropdown-divider"></div>
        <li><%= link_to 'Logout', logout_path, method: :delete, class: 'dropdown-item' %></li>


      </div>
    </div>
  <% else %>
    <li><%= link_to "Log in", login_path %></li>
  <% end %>
</nav>

app/views/layouts/_tobe_navigation_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-between">
  <%= link_to "Base App", root_path, :class => "navbar-brand" %>
    <ul class="navbar-nav ml-auto">
    <li class="nav-item active">
      <%= link_to "Home", root_path, :class => "nav-link" %>
    </li>
  </ul>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav-bar-collapse" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <% if logged_in? %>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <%= link_to "Rooms", '#', :class => "nav-link" %>
      </li>
    </ul>
    <div class="dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <img class="avatar" src="<%= gravatar_url(current_user) %>" alt="Piccie">
        <%= current_user.name %>
      </a>

      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <%= link_to 'Logout', logout_path, method: :delete, class: 'dropdown-item' %>
      </div>
    </div>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
   <title><%= yield(:title) %> | Base Rails App</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-12">
          <%= render partial: 'layouts/navigation_bar' %>
          <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>"><%= message %></div>
          <% end %>          
            <%= yield %>
          <%= render partial: 'layouts/debug' %>
          <%= render partial: 'layouts/footer' %>
        </div>
      </div>
    </div>
  </body>
</html>